### PR TITLE
Add docs for `libredox` and `common` + Small changes + Style cleanup (`return` statements)

### PR DESCRIPTION
**Pull request by Ticki**
Remove many of the `return` statements, replacing them by expressions instead.

### CODE REVIEW

**Comment by stratact** [comment]
Good catch!

**Comment by Ticki** [comment]
I just added a commit with docs for `libredox` and `common`

**Comment by Ticki** [comment]
Is the logo too big? See README.txt.

**Comment by jackpot51** [comment]
Merging this in now. The conflicts were between the docs and the function brace spacing from #19

**Pull request merged**
